FROM almalinux:9 
# CMD ["ping", "google.com"]
# ENTRYPOINT ["ping", "facebook.com"]

CMD ["google.com"]
ENTRYPOINT ["ping"]

# CMD command can be override anytime in runtime
# ENTRY POINT command cannot be overwritten in runtime